<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JugadoresSeeder extends Seeder
{
    public function run()
    {
        DB::table('jugadores')->insert([
            [
                'nombre' => 'Carlsen',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747030652/Carlsen.webp',
                'posicion' => 'Top',
                'equipo_real' => 'Team Heretics',
                'valor' => 120000000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Sheo',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747030653/Sheo.webp',
                'posicion' => 'Jungla',
                'equipo_real' => 'Team Heretics',
                'valor' => 120000000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Kamiloo',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747030652/Kamiloo.webp',
                'posicion' => 'Mid',
                'equipo_real' => 'Team Heretics',
                'valor' => 120000000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Flakked',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747030652/Flakked.webp',
                'posicion' => 'Adc',
                'equipo_real' => 'Team Heretics',
                'valor' => 120000000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Stend',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747030653/Stend.webp',
                'posicion' => 'Support',
                'equipo_real' => 'Team Heretics',
                'valor' => 120000000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'BrokenBlade',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747033577/BrokenBlade.webp',
                'posicion' => 'Top',
                'equipo_real' => 'G2',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'SkewMond',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747033578/SkewMond.webp',
                'posicion' => 'Jungla',
                'equipo_real' => 'G2',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Caps',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747033577/Caps.webp',
                'posicion' => 'Mid',
                'equipo_real' => 'G2',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Hans Sama',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747033578/Hans_Sama.webp',
                'posicion' => 'Adc',
                'equipo_real' => 'G2',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Labrov',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747033578/Labrov.webp',
                'posicion' => 'Support',
                'equipo_real' => 'G2',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Oscarinin',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747034202/Oscarinin.webp',
                'posicion' => 'Top',
                'equipo_real' => 'Fnatic',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Razork',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747034207/Razork.webp',
                'posicion' => 'Jungla',
                'equipo_real' => 'Fnatic',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Humanoid',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747034202/Humanoid.webp',
                'posicion' => 'Mid',
                'equipo_real' => 'Fnatic',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Upset',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747034207/Upset.webp',
                'posicion' => 'Adc',
                'equipo_real' => 'Fnatic',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Mikyx',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747034202/Mikyx.webp',
                'posicion' => 'Support',
                'equipo_real' => 'Fnatic',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Canna',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747035643/Canna_cbtivr.webp',
                'posicion' => 'Top',
                'equipo_real' => 'Karmine Corp',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Yike',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747035643/Yike_p3bsps.webp',
                'posicion' => 'Jungla',
                'equipo_real' => 'Karmine Corp',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Vladi',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747035643/Vladi_ylw0tz.webp',
                'posicion' => 'Mid',
                'equipo_real' => 'Karmine Corp',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Caliste',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747035643/Caliste_kqirqs.webp',
                'posicion' => 'Adc',
                'equipo_real' => 'Karmine Corp',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Targamas',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747035643/Targamas_xlnqak.webp',
                'posicion' => 'Support',
                'equipo_real' => 'Karmine Corp',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Myrwn',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747039877/Myrwn_uooxvx.webp',
                'posicion' => 'Top',
                'equipo_real' => 'Movistar KOI',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Elyoya',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747039878/Elyoya_i4ibty.webp',
                'posicion' => 'Jungla',
                'equipo_real' => 'Movistar KOI',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Jojopyun',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747039953/Jojopyun_r7wb7o.webp',
                'posicion' => 'Mid',
                'equipo_real' => 'Movistar KOI',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Supa',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747039954/Supa_oxi8jr.webp',
                'posicion' => 'Adc',
                'equipo_real' => 'Movistar KOI',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Alvaro',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747039877/Alvaro_g4bcpl.webp',
                'posicion' => 'Support',
                'equipo_real' => 'Movistar KOI',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Naak Nako',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747040218/Naak_Nako_aennui.webp',
                'posicion' => 'Top',
                'equipo_real' => 'Team Vitality',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Lyncas',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747040217/Lyncas_jqcfdy.webp',
                'posicion' => 'Jungla',
                'equipo_real' => 'Team Vitality',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Czajek',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747040138/Czajek_m2zpzm.webp',
                'posicion' => 'Mid',
                'equipo_real' => 'Team Vitality',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Carzzy',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747040138/Carzzy_lcgqlu.webp',
                'posicion' => 'Adc',
                'equipo_real' => 'Team Vitality',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Nisqy',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747040220/Nisqy_bxv2kn.webp',
                'posicion' => 'Support',
                'equipo_real' => 'Team Vitality',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Irrelevant',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747040516/Irrelevant_ikhi6r.webp',
                'posicion' => 'Top',
                'equipo_real' => 'BDS',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => '113',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747040512/113_ect0ne.webp',
                'posicion' => 'Jungla',
                'equipo_real' => 'BDS',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Nuc',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747040517/nuc_dxjkur.webp',
                'posicion' => 'Mid',
                'equipo_real' => 'BDS',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Ice',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747040514/Ice_rvicy9.webp',
                'posicion' => 'Adc',
                'equipo_real' => 'BDS',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Parus',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747040511/Parus_wa2yuc.webp',
                'posicion' => 'Support',
                'equipo_real' => 'BDS',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'JNX',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747040887/JNX_jkshk8.webp',
                'posicion' => 'Top',
                'equipo_real' => 'SK',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Boukada',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747040888/Boukada_xcc5td.webp',
                'posicion' => 'Jungla',
                'equipo_real' => 'SK',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Reeker',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747040891/Reeker_zw6j6d.png',
                'posicion' => 'Mid',
                'equipo_real' => 'SK',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Keduii',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747040890/Keduii_hfdnjd.webp',
                'posicion' => 'Adc',
                'equipo_real' => 'SK',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Loopy',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747041036/Loopy_rrnguy.png',
                'posicion' => 'Support',
                'equipo_real' => 'SK',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Lot',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747041194/Lot_qz5k3u.webp',
                'posicion' => 'Top',
                'equipo_real' => 'GiantX',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Isma',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747041192/ISMA_npenxk.webp',
                'posicion' => 'Jungla',
                'equipo_real' => 'GiantX',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Jakies',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747041196/Jackies_vzusfe.webp',
                'posicion' => 'Mid',
                'equipo_real' => 'GiantX',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Noah',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747041199/Noah_xht0gx.webp',
                'posicion' => 'Adc',
                'equipo_real' => 'GiantX',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Jun',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747041198/Jun_b413us.webp',
                'posicion' => 'Support',
                'equipo_real' => 'GiantX',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Adam',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747041513/Adam_tnr99z.webp',
                'posicion' => 'Top',
                'equipo_real' => 'Rogue',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Malrang',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747041520/Malrang_s29lvx.webp',
                'posicion' => 'Jungla',
                'equipo_real' => 'Rogue',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Larssen',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747041516/Larssen_x6jm3b.webp',
                'posicion' => 'Mid',
                'equipo_real' => 'Rogue',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Patrik',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747041514/Patrik_w57fh4.webp',
                'posicion' => 'Adc',
                'equipo_real' => 'Rogue',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
            [
                'nombre' => 'Execute',
                'imagen_url' => 'https://res.cloudinary.com/dpsvxf3qg/image/upload/v1747041518/Execute_ja30ac.webp',
                'posicion' => 'Support',
                'equipo_real' => 'Rogue',
                'valor' => rand(3000, 9000) * 10000,
                'puntos' => 0,
            ],
        ]);
    }
}
